name: Release and Upload Nuget

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build --configuration Release

      - name: Package
        run: >
          dotnet pack --no-restore --no-build --configuration Release 
          -p:PackageVersion=${{ github.ref_name }} --output .

      - name: Publish
        run: >
          dotnet nuget push Anov.${{ github.ref_name }}.nupkg 
          -s https://nuget.pkg.github.com/Lemon73-Computing/index.json 
          -k ${{ secrets.NUGET_AUTH_TOKEN }}
